name: 'Test'

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test_workflow.yml'

jobs:
  update_psalm_baseline:
    name: 'Psalm: update baseline'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Produce test output
        id: output_something
        run: ls -la

      - name: Test join
        run: echo ${{ join(steps.output_something.outputs.*, '\n') }}

      - name: Submit Psalm output to store stats
        run: |
          curl -X POST https://script.google.com/macros/s/AKfycbzjLGk5RWNmNOHLQUhCH1vToqAyvm_16UkNr8Hin--5g7QD8ziEZPcZnWlefUVZlln7Xw/exec \
          -H 'Content-Type: application/json' \
          -H 'Accept: application/json' \
          -d '{"output": "${{ toJSON(join(steps.output_something.outputs.*, '\n')) }}" }'
